name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Spaces README config
        run: cp -f docker/README.md .
      
      - name: Copy Dockerfile to root
        run: cp docker/Dockerfile .

      - name: Copy app.py to root
        run: cp src/ferret/app.py .

      - name: Push to HuggingFace Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://<HF_USER>:$HF_TOKEN@huggingface.co/spaces/FuturePrompters/apples-ferret main
