name: Deploy to HF Spaces

on:
  push:
    branches:
      - main

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to HuggingFace Spaces
        env:
          HF_USERNAME: ${{ vars.HF_USERNAME }}
          SPACE_NAME: ${{ vars.SPACE_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main
